package domain

// ChapterPlan is the writing plan of a chapter, generated autonomously by the Writer.
// Scene splitting is no longer enforced; the Agent decides on its own how to organize the content.
type ChapterPlan struct {
	Chapter    int             `json:"chapter"`
	Title      string          `json:"title"`
	Goal       string          `json:"goal"`
	Conflict   string          `json:"conflict"`
	Hook       string          `json:"hook"`
	EmotionArc string          `json:"emotion_arc,omitempty"`
	Notes      string          `json:"notes,omitempty"` // free-form memo of the Agent
	Contract   ChapterContract `json:"contract,omitempty"`
}

// ChapterContract is the chapter acceptance contract shared by the Writer and the Editor.
// It defines the beats this chapter must deliver, the moves it must not make, and the review focus points.
type ChapterContract struct {
	RequiredBeats    []string `json:"required_beats,omitempty"`    // the beats this chapter must land
	ForbiddenMoves   []string `json:"forbidden_moves,omitempty"`   // the moves that explicitly must not happen in this chapter
	ContinuityChecks []string `json:"continuity_checks,omitempty"` // the continuity points to double-check especially in this chapter
	EvaluationFocus  []string `json:"evaluation_focus,omitempty"`  // the points the Editor has to examine closely
	EmotionTarget    string   `json:"emotion_target,omitempty"`    // optional: the emotion the reader should mainly feel in this chapter
	PayoffPoints     []string `json:"payoff_points,omitempty"`     // optional: the plot points/payoff points a key chapter wants to answer
	HookGoal         string   `json:"hook_goal,omitempty"`         // optional: the desire to keep reading that the end-of-chapter hook should drive
}

// ChapterSummary is the chapter summary, used by the context window of the following chapters.
type ChapterSummary struct {
	Chapter    int      `json:"chapter"`
	Title      string   `json:"title"`
	Summary    string   `json:"summary"`
	Characters []string `json:"characters"`
	KeyEvents  []string `json:"key_events"`
}

// ArcSummary is the arc-level summary, generated by the Editor when the arc ends.
type ArcSummary struct {
	Volume    int      `json:"volume"`
	Arc       int      `json:"arc"`
	Title     string   `json:"title"`
	Summary   string   `json:"summary"`
	KeyEvents []string `json:"key_events"`
}

// VolumeSummary is the volume-level summary, generated when the volume ends.
type VolumeSummary struct {
	Volume    int      `json:"volume"`
	Title     string   `json:"title"`
	Summary   string   `json:"summary"`
	KeyEvents []string `json:"key_events"`
}

// CharacterSnapshot is a character state snapshot, recorded at an arc boundary.
type CharacterSnapshot struct {
	Volume     int    `json:"volume"`
	Arc        int    `json:"arc"`
	Name       string `json:"name"`
	Status     string `json:"status"`
	Power      string `json:"power,omitempty"`
	Motivation string `json:"motivation"`
	Relations  string `json:"relations,omitempty"`
}

// OutlineFeedback is the Writer's feedback on the outline, optional when committing a chapter.
type OutlineFeedback struct {
	Deviation  string `json:"deviation"`  // the description of the deviation
	Suggestion string `json:"suggestion"` // the adjustment suggestion
}

// WritingStyleRules are the writing rules distilled from the chapters already written, generated by the Editor at an arc boundary.
// It replaces the raw text excerpts (style_anchors / voice_samples), using rules instead of carrying over raw text.
type WritingStyleRules struct {
	Volume    int              `json:"volume"`
	Arc       int              `json:"arc"`
	Prose     []string         `json:"prose"`      // 3-5 prose style rules, each <= 50 characters
	Dialogue  []CharacterVoice `json:"dialogue"`   // the dialogue style rules of a character
	Taboos    []string         `json:"taboos"`     // the list of taboos
	UpdatedAt string           `json:"updated_at"` // an ISO8601 timestamp
}

// CharacterVoice is the dialogue style rule of a single character.
type CharacterVoice struct {
	Name  string   `json:"name"`
	Rules []string `json:"rules"` // 2-3 language-feature rules, each <= 30 characters
}

// RelatedChapter is a recommended chapter to re-read.
type RelatedChapter struct {
	Chapter int    `json:"chapter"`
	Reason  string `json:"reason"`
}

// RecallItem is long-term information selectively recalled for the current task.
// It does not replace the formal artifacts; it only re-injects the few genuinely relevant pieces of history into the model for the current turn.
type RecallItem struct {
	Kind    string `json:"kind"`
	Key     string `json:"key,omitempty"`
	Chapter int    `json:"chapter,omitempty"`
	Reason  string `json:"reason,omitempty"`
	Summary string `json:"summary,omitempty"`
}

// CommitResult is the structured return value of the commit_chapter tool.
// It only contains fact fields; "what to do next" is generated by the Reminder channel on its own from the current Progress.
type CommitResult struct {
	Chapter        int              `json:"chapter"`
	Committed      bool             `json:"committed"`
	WordCount      int              `json:"word_count"`
	NextChapter    int              `json:"next_chapter"`
	ReviewRequired bool             `json:"review_required"`
	ReviewReason   string           `json:"review_reason,omitempty"`
	HookType       string           `json:"hook_type,omitempty"`
	DominantStrand string           `json:"dominant_strand,omitempty"`
	Feedback       *OutlineFeedback `json:"feedback,omitempty"`
	// long-form layered signals
	ArcEnd         bool `json:"arc_end,omitempty"`
	VolumeEnd      bool `json:"volume_end,omitempty"`
	Volume         int  `json:"volume,omitempty"`
	Arc            int  `json:"arc,omitempty"`
	NeedsExpansion bool `json:"needs_expansion,omitempty"`  // the next arc is a skeleton and needs its chapters expanded
	NeedsNewVolume bool `json:"needs_new_volume,omitempty"` // the Architect needs to create the next volume
	NextVolume     int  `json:"next_volume,omitempty"`      // the number of the next arc/volume
	NextArc        int  `json:"next_arc,omitempty"`         // the number of the next arc
	// completion fact: whether the whole book is done after this commit
	BookComplete bool `json:"book_complete,omitempty"`
	// a snapshot of the current Progress.Flow (writing / reviewing / rewriting / polishing)
	Flow string `json:"flow,omitempty"`
}
